version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
  test:
    docker:
      - image: circleci/node:8.0
    steps:
      - checkout
      - run: env
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
